# Generated by Django 2.2.7 on 2019-11-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=120, verbose_name='URL')),
                ('text', models.TextField(verbose_name='Текст категории')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Баннер')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('description', models.CharField(max_length=120, verbose_name='Description')),
                ('keywords', models.CharField(max_length=120, verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название услуги')),
                ('slug', models.SlugField(default='', max_length=120, unique=True, verbose_name='URL')),
                ('text', models.TextField(default='', verbose_name='Текст модели')),
                ('header', models.CharField(blank=True, max_length=120, null=True, verbose_name='Заголовок')),
                ('sub_header', models.CharField(blank=True, max_length=120, null=True, verbose_name='Подзаголовок')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка')),
                ('active', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('kyewords', models.CharField(max_length=250, verbose_name='Kyewords')),
                ('sort', models.CharField(default=0, max_length=250, unique=True, verbose_name='Порядок')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Banner')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Category', verbose_name='Выбор категории')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
    ]
