# Generated by Django 2.2.6 on 2019-12-08 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_model_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='kyewords',
        ),
        migrations.AddField(
            model_name='model',
            name='keywords',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='Keywords'),
            preserve_default=False,
        ),
    ]
