# Generated by Django 2.2.6 on 2019-12-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20191208_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='keywords',
            new_name='kyewords',
        ),
    ]
